logging:
  level:
    ROOT: INFO
    org.springframework.jdbc.core: TRACE
    io.devandre.furtmates: DEBUG

spring:
  web:
    resources:
      add-mappings: false
  application:
    name: Furtmates-Backend
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/furtmates-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jdbc:
    template:
      fetch-size: 100
      max-rows: 500

  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: furtmates_schema
    contexts: dev
    enabled: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    version: 1.0.0
    operations-sorter: method
    tags-sorter: alpha
    default-model-expand-depth: -1
  show-actuator: true